
# Environment Base URL
@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/api/v1/workouts/

###
# POST request to add a new exercise
POST {{baseUrl}}/api/v1/workouts/add
Content-Type: application/json

{
  "userId": 123456,
  "workoutId": "4",
  "name": "inserted",
  "duration": "30 minutes",
  "calories": 300,
  "date": "2023-12-08"
}

###
# GET request to retrieve exercises for a specific user
GET {{baseUrl}}/api/v1/workouts/user/123456

###
GET {{baseUrl}}/api/v1/workouts/user/1


###
GET {{baseUrl}}/api/v1/workouts/

###
PUT {{baseUrl}}/api/v1/workouts/update/workout/657544eddb6d17b8d436666f
Content-Type: application/json

{
  "complete": false
}


###
# DELETE request to delete an exercise (replace <exerciseId> with actual ID)
DELETE {{baseUrl}}/api/v1/workouts/delete/workout/6574b2e90ee70f9742db6d0a

### 
DELETE {{baseUrl}}/api/v1/workouts/deleteAll/user/123456



